### PR TITLE
Updated some styling and responsive issues

### PR DESCRIPTION
**Pull request by jgudo**
I did some style changes bradder. 

- Set header as fixed for better navigation
- Responsive issues in newsletter form
- Some ui improvements
Changes

### CODE REVIEW

**Review by condinoaljoseph — CHANGES_REQUESTED** [review]
Thanks for the wonderful PR bro. I like how you update my pagination. it's cool man and thanks for fixing responsiveness of the form. But I think i go with my previous header. I want to make it look as the inspiration of this blog which is from [overreacted.io](https://overreacted.io/).

**Comment by condinoaljoseph** [comment]
you can check also the preview of your PR here: [https://aljoseph-git-fork-jgudo-enhancement-style-changes.condinoaljoseph.vercel.app/](https://aljoseph-git-fork-jgudo-enhancement-style-changes.condinoaljoseph.vercel.app/). Thanks

**Comment by jgudo** [comment]
Got you bro. I've never seen Dan's blog before so I had no idea.

**Comment by condinoaljoseph** [comment]
Im gonna close this since the latest branch has many changes and can conflict other files. I also remove redis integration. I am currently accepting PR that will solve the open issues. Thanks!

**Pull request closed without merging**
